// Auto-generated by agents/devops_agent.py for the 'nonprod' environment.
// Estimated monthly cost from the plan: ~$21.16 (budget cap set 25% above this).
using '../main.bicep'

param environmentName = 'nonprod'
param location = 'australiaeast'
param appName = 'coaching-platform'
param monthlyBudgetUsd = 26
param costAlertEmail = 'hamish.armstrong88@gmail.com'
// Supplied at compile time from environment variables (the pipeline maps each
// one from a secret variable in the 'coaching-platform-common' variable group);
// never committed to source control. These are written into Key Vault by
// main.bicep and reach the app as @Microsoft.KeyVault() references.
param postgresAdminPassword = readEnvironmentVariable('POSTGRES_ADMIN_PASSWORD')
param djangoAdminPassword = readEnvironmentVariable('DJANGO_ADMIN_PASSWORD')
param djangoSecretKey = readEnvironmentVariable('DJANGO_SECRET_KEY')
param resendApiKey = readEnvironmentVariable('RESEND_API_KEY')
