// Auto-generated by agents/devops_agent.py for the 'nonprod' environment.
// Estimated monthly cost from the plan: ~$21.16 (budget cap set 25% above this).
using '../main.bicep'

param environmentName = 'nonprod'
param location = 'uksouth'
param appName = 'coaching-platform'
param monthlyBudgetUsd = 26
param costAlertEmail = 'REPLACE_ME@example.com'
// Supplied at compile time from the POSTGRES_ADMIN_PASSWORD environment variable
// (the pipeline maps it from the secret variable 'postgresAdminPassword');
// never committed to source control.
param postgresAdminPassword = readEnvironmentVariable('POSTGRES_ADMIN_PASSWORD')
