// Auto-generated by agents/devops_agent.py for the 'prod' environment.
// Estimated monthly cost from the plan: ~$113.67 (budget cap set 25% above this).
using '../main.bicep'

param environmentName = 'prod'
param location = 'uksouth'
param appName = 'coaching-platform'
param monthlyBudgetUsd = 142
param costAlertEmail = 'REPLACE_ME@example.com'
// postgresAdminPassword must be supplied at deploy time via --parameters or a pipeline secret variable,
// never committed to source control.
