// Auto-generated by agents/devops_agent.py - edit the agent, not this file.
targetScope = 'resourceGroup'

@description('Environment name: nonprod or prod')
@allowed(['nonprod', 'prod'])
param environmentName string

@description('Azure region for all resources')
param location string = 'australiaeast'

@description('Region for the Static Web App -- Microsoft.Web/staticSites is only available in centralus, eastus2, westus2, westeurope and eastasia; eastasia preflight rejects new sites on this subscription, so westus2 is used')
param staticWebAppLocation string = 'westus2'

@description('Region for the auto-shutdown Automation account -- Free Trial/Student subscriptions can only create them in eastus, eastus2, westus, northeurope, southeastasia and japanwest')
param automationLocation string = 'southeastasia'

@description('Application name used as a resource naming prefix')
param appName string = 'coaching-platform'

@description('Hard monthly budget cap in USD for this environment (cost-management guardrail)')
param monthlyBudgetUsd int = environmentName == 'prod' ? 400 : 100

@description('Email address to receive budget/cost alerts')
param costAlertEmail string

@description('PostgreSQL administrator login name')
param postgresAdminLogin string = 'coachadmin'

@description('PostgreSQL administrator password (pass via --parameters at deploy time, never commit it)')
@secure()
param postgresAdminPassword string

@description('Initial password for the seeded Django staff user (change forced on first login)')
@secure()
param djangoAdminPassword string

var tags = {
  application: appName
  environment: environmentName
  managedBy: 'devops-agent'
}

module logAnalytics 'modules/logAnalytics.bicep' = {
  name: 'logAnalytics'
  params: {
    appName: appName
    environmentName: environmentName
    location: location
    tags: tags
  }
}

module appInsights 'modules/appInsights.bicep' = {
  name: 'appInsights'
  params: {
    appName: appName
    environmentName: environmentName
    location: location
    tags: tags
    logAnalyticsWorkspaceId: logAnalytics.outputs.workspaceId
  }
}

module keyVault 'modules/keyVault.bicep' = {
  name: 'keyVault'
  params: {
    appName: appName
    environmentName: environmentName
    location: location
    tags: tags
  }
}

module storage 'modules/storageAccount.bicep' = {
  name: 'storage'
  params: {
    appName: appName
    environmentName: environmentName
    location: location
    tags: tags
  }
}

module postgres 'modules/postgresFlexibleServer.bicep' = {
  name: 'postgres'
  params: {
    appName: appName
    environmentName: environmentName
    location: location
    tags: tags
    administratorLogin: postgresAdminLogin
    administratorPassword: postgresAdminPassword
  }
}

module backendApp 'modules/appService.bicep' = {
  name: 'backendApp'
  params: {
    appName: appName
    environmentName: environmentName
    location: location
    tags: tags
    appInsightsConnectionString: appInsights.outputs.connectionString
    keyVaultUri: keyVault.outputs.vaultUri
    staticWebAppHostname: staticWebApp.outputs.defaultHostName
    postgresHost: postgres.outputs.fullyQualifiedDomainName
    postgresDatabase: postgres.outputs.databaseName
    postgresAdminLogin: postgresAdminLogin
    postgresAdminPassword: postgresAdminPassword
    djangoAdminPassword: djangoAdminPassword
  }
}

module staticWebApp 'modules/staticWebApp.bicep' = {
  name: 'staticWebApp'
  params: {
    appName: appName
    environmentName: environmentName
    location: staticWebAppLocation
    tags: tags
  }
}

module costGuardrails 'modules/costGuardrails.bicep' = {
  name: 'costGuardrails'
  params: {
    appName: appName
    environmentName: environmentName
    monthlyBudgetUsd: monthlyBudgetUsd
    costAlertEmail: costAlertEmail
  }
}

module autoShutdown 'modules/autoShutdown.bicep' = if (environmentName == 'nonprod') {
  name: 'autoShutdown'
  params: {
    appName: appName
    environmentName: environmentName
    location: automationLocation
    tags: tags
    webAppName: backendApp.outputs.webAppName
    postgresServerName: postgres.outputs.serverName
  }
}

output backendUrl string = backendApp.outputs.defaultHostName
output frontendUrl string = staticWebApp.outputs.defaultHostName
output postgresServerName string = postgres.outputs.serverName
